Make button text editable in studio, improve layout
pmitros/DoneXBlock pull request #11
Opened 2018-09-05 23:27 UTC by bryanlandia

This makes the layout alignment (left/right), and before and after (undone / done) button text editable via a Studio edit form view from `xblock-utils`, a new dependency.  

## Studio preview (done state)
<img width="970" alt="screen shot 2018-09-06 at 1 22 16 am" src="https://user-images.githubusercontent.com/1289191/45126391-78275880-b173-11e8-9877-57637dc485f9.png">

## Studio edit form, with defaults
<img width="1232" alt="screen shot 2018-09-06 at 1 25 42 am" src="https://user-images.githubusercontent.com/1289191/45126473-d94f2c00-b173-11e8-84ce-7212f9dfbded.png">

## Studio edit form with custom button text values
<img width="1262" alt="screen shot 2018-09-06 at 1 22 28 am" src="https://user-images.githubusercontent.com/1289191/45126390-778ec200-b173-11e8-9343-cea5831fbfdc.png">

## Student view (not  done state)
<img width="814" alt="screen shot 2018-09-06 at 1 22 57 am" src="https://user-images.githubusercontent.com/1289191/45126389-778ec200-b173-11e8-9ca4-fc69b1f9042b.png">

2018-09-06 13:26 UTC, OmarIthawi requested changes
Thanks @bryanlandia! I've taken a quick look here. This pull request will need another detailed review once the points below are addressed:

 - [ ] Let's wait for #10 to be merged first, it will be pretty useful to avoid the layout and `content` hacks, and should have a better layout model.
 - [ ] Once this is merged, let's also make the `display_name` editable, since it will bug mobile users with unlocalized and un-editable section titles (like currently on master)
 - [ ] The `Scope.content` changes needs to be explained in details to make sure that I understand both of the rationale and the method for the change.
 - [ ] The `install_requires` should rarely be changed, especially for the `XBlock` version as it could be problematic for other XBlocks.

2018-09-26 17:12 UTC, OmarIthawi commented
@bryanlandia Please let me know if you're still planning to work on this PR. 

FYI, Since #10 has been merged this PR has some conflicts now -- which is OK, but it means that this PR should be refactored to address them.

2020-12-09 13:31 UTC, OmarIthawi commented
@bryanlandia could you please share the status of this PR?

2021-01-05 21:01 UTC, bryanlandia commented
@OmarIthawi I think the changes in general are still useful though clearl need some updating.  I will need to spend a little time reviewing.  My plan is to do that week of 2020-1-12

2025-02-08 00:30 UTC, closed without merging